apiVersion: v1
kind: Service
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: firstapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
